### ISSUE TITLE
Image uploads into the rich text editor no longer resolve properly after an upgrade

### ISSUE THREAD

**Issue by dr01d3r** [vanderbilt/redcap-external-modules#104]
https://github.com/vanderbilt/redcap-external-modules/blob/42983f07b14de94366b7edfafbd555a69a601ff9/manager/rich-text/get-uploaded-file-list.php#L119

Uploaded content in the RTE is saved with the full versioned path.  After an upgrade, images no longer render as expected.  I need to go into the database and globally update all references to the current REDCap version, or manually go into each project's EM config and update via the raw code view.

Looking for a non-versioned way to store this content so it handles upgrades a bit more gracefully.

**Comment by mmcev106** [comment]
It looks like we haven't encountered this issue because we use the "override" location for the external modules core code (instead of the version inside the redcap version dir).  After the rich text editor was added, we made it possible to make module requests via the "/api" path.  I think changing the rich text editor to use "/api" urls for embedded images would fix the problem in a way that would still work if the EM core directory was ever overridden.  I'll also look into using relative paths while I'm at it.  Stay tuned...

**Comment by mmcev106** [comment]
I just created this pull request:

https://github.com/vanderbilt/redcap-external-modules/pull/120

@dr01d3r, I think the solution is solid, but I'd love to hear any feedback you might have on it.

**Comment by dr01d3r** [comment]
From the looks of it, this ends up saving the new versionless url in the module config.  Will anything need to happen with legacy uploads?

**Comment by 123andy** [comment]
Any thoughts about how a new 'versionless' endpoint (other than API) could help solve this as it applies not only to EMs but also to some bookmarks, emails, etc...

**Comment by mmcev106** [comment]
@dr01d3r, legacy URLs will still work (until the REDCap version changes).  To switch to the new URLs, images/media will need to be removed, re-added, and saved for each popup.  Existing file uploads can still be when re-adding images/media.

**Comment by mmcev106** [comment]
@123andy, at the moment adding another endpoint doesn't seem like it would add any value.  I already view EM's index.php as our real endpoint, and the API is a simple pass through.   That's why I don't think we should put additional logic at the API endpoint (not even NOAUTH handling), as it will limit our control in EM's index.php.  If the code mentioned in issue #119 if really the simplest fix, then I think we have a fundamental design issue elsewhere that should and could be simplified without adding any additional moving parts.

**Comment by 123andy** [comment]
Mark - my patch is to restore function but still leaves a fundamental issue that needs to be addressed with shibboleth sites...  Some tweaking in the bootstrap process of API/index.php might get around this if we delay the System::initGlobalPage() until AFTER the ExternalModules/index.php...  Happy to discus options.

**Comment by mmcev106** [comment]
I definitely think delaying System::initGlobalPage() until after ExternalModules/index.php would be a good move to make sure we have the freedom/control we need to evolve.

**Comment by mmcev106** [comment]
PR #120 has been merged, and should resolve this.  Closing...
