### ISSUE TITLE
Thoughts on autoloading certain classes or traits?

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#123]
Seems like we're coming across a common theme of having 'utility' functions we'd like to include with our em.  Currently, we copy them and namespace them all to each EM to prevent collisions. 

Ideally, we could leave them in their 'proper' utility namespace independent of the actual EM but still be able to access the methods...  

Any ideas on this?

**Comment by dr01d3r** [comment]
I had this very problem when I started making my second EM.  A trait was defined in both modules with the same shared namespace, causing a collision.

One thing we can't avoid is including the file with each module.  If they are in a utility namespace, how do we tell autoloader to use the one packaged with Shazam instead of Orca Search?  We probably dont want that anyway, due to versioning or compatibility issues.

What if there was a way to have a single source for a file?  Some form of DI or shared file hosting?

**Comment by dr01d3r** [comment]
Has anything like this been done for a similar environment, like Wordpress?

**Comment by mmcev106** [comment]
Drupal allows for inter-module dependencies.  For example, a module can require that a specific version of another module be enabled first.  We could implement this.

If I had to do this today, I would use composer to load my shared lib on both modules just like any third party library.  While that prevents conflicts, the first version of the shared lib will be used for all modules, which can cause issues depending on the shared lib versions and what features are being used.  This is guaranteed to be safe if the version of the shared lib required is in sync across all modules.  I believe this is what most people do in the WordPress world.

**Comment by mmcev106** [comment]
Closing since this has not been updated in over a year.  Feel free to reopen.
