### ISSUE TITLE
Display a link to the changes included in a module version (perhaps GitHub commits)

### ISSUE THREAD

**Issue by mmcev106** [vanderbilt/redcap-external-modules#139]
Requested by Adam Lewis

**Comment by pbchase** [comment]
Listing the commits could be automated, but the result might be low quality. I harp on my devs to use good commit messages, but even when they are good, the messages are often expressed in terms only a developer would love. I write ChangeLog entries for each release and they are often vastly shorter and a good bit different from the list of commits since the previous release.

**Comment by mmcev106** [comment]
Closing in favor of #230
