### ISSUE TITLE
Do keys have to be unique between project and global settings?

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#156]
https://github.com/vanderbilt/redcap-external-modules/blob/b7e404c083cd505c8435d8cd856f2feda1b6cef7/classes/AbstractExternalModule.php#L63

This caused a working EM to fail on upgrade due to using the same setting key for a project and system level setting.  Is there a valid reason this shouldn't be allowed?  IF not, does this function need to differentiate between project and system settings?

**Comment by mmcev106** [comment]
Explaining this involves some history, but before I do, is your module defining a constructor without calling the parent constructor per chance?  That is where invalid settings are checked, so it shouldn't be possible to even instantiate a module during development with a duplicate setting in place.  I just created [this issue](https://github.com/vanderbilt/redcap-external-modules/issues/157) to consider this further as some point.

Settings were originally designed so that system settings could be overridden at the project level (so keys were not allowed to overlap between the two).  We later removed this from the UI because it added some complexity and we only ever used it in a few cases.  However, it is still in place on the back end.  For example, if you define a setting only at the system level, then call **getProjectSetting()** the system value will be returned (like a default).  We could and perhaps should remove this rarely used "feature", but it would require some refactoring framework and perhaps any modules that depend on the current behavior.

**Comment by 123andy** [comment]
Hey Mark,

1) No - the parent constructor is called:
```php
    public function __construct()
    {
        parent::__construct();

        // If in project context, load the object
        global $project_id;
        if ($project_id) {
            $this->emDebug("Loading " . self::TOKEN_KEY . " for project $project_id");
            $this->email_token = $this->getProjectSetting(self::TOKEN_KEY, $project_id);
        }

        $this->emDebug($this->PREFIX . " constructed $project_id");
    }
```

2. That makes sense -- thanks for explaining it so clearly.  It wasn't a big deal for me to fix on this module, but that is good to know.  So what you're saying is that a module in project context should really only use **getProjectSetting()**.  Without a lot of thought, I'd probably say this, while potentially useful, adds some confusion and would be in favor of leaving the two scopes separate, but I don't feel that strongly about it.  Thanks for all your work and effort in maintaining and supporting this!

 Andy

**Comment by mmcev106** [comment]
@123andy, I'm not sure how the update made it that far without triggering that error during development.  I'd be curious if you have any insights there.

Your feedback is always very much appreciated as well Andy.  Thank you!
