### ISSUE TITLE
cron jobs

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#16]
I've got a number of 'enhancements' that are dependent on a cron job.  Any thoughts on how to incorporate a cron task to the `config.json`?  Perhaps we need to add a 'modules' cron job that calls some global ExternalModules cron scanner every 15 minutes or so...

**Comment by scottjpearson** [comment]
I like this concept, but I'd suggest we also allow for non-repeatable events to be enqueued. So repeatable (coded in a manner compatible with crown) and one-time in mm-dd-yyyy hh:mm.

Get Outlook for iOS<https://aka.ms/o0ukef>



On Tue, Aug 8, 2017 at 7:54 PM -0500, "Andy Martin" <notifications@github.com<mailto:notifications@github.com>> wrote:


I've got a number of 'enhancements' that are depending on a cron job. Any thoughts on how to incorporate a cron task to the config.json? Perhaps we need to add a 'modules' cron job that calls some global ExternalModules cron scanner every 15 minutes or so...

**Comment by taylorr4** [comment]
@scottjpearson, i'm not quite sure i follow you. Are you talking repeating events type functionality? If so, i believe the cron idea is much broader and simpler an idea.

@123andy, I like this idea. I imagine it would have to be pretty simple though. REDCap could call a global ExternalModules cron job every X minutes, it could scan all module configs for a "crons" attribute (for example), and then execute the method(s) listed in the "crons" attribute (like in the JSON below, or maybe it could just be a single method, since it could ostensibly call them all if there are many methods to run). The limitation would be that there doesn't seem to be an easy way to call an individual module's cron at specific times but just always execute a module's cron method every time. Doing anything more complicated would require building an extra crons db table in REDCap to handle running module crons at specific intervals as specified in the config and then keeping track to ensure a module cron doesn't run again until the next interval. Its not impossible but would take a bit more work. Should we just keep it simple?

"crons": [
	"module_method_1",
	"module_method_2"
]

or instead
"cron": "module_cron_method"

**Comment by scottjpearson** [comment]
@Robtaylor, I was trying to agree with @123andy, but wasn’t on a keyboard. Sorry. I was also trying to point out that the scheduling aspect of a cron (when it runs) should probably support repeating launches and one-time launches. The UNIX cron interface only supports repeating launches, and I believe this to be a bad limitation. For instance, I am launching a cron on Thursday to send a batch of emails. If I leave this cron around until 2018, it will launch again because my cron has no one-time launch support.

Granted, a one-time launch mechanism would probably not be very generalizable. Maybe this should be support by a parameter within the module’s configuration in the JavaScript layer.

Do I make sense now?

**Comment by 123andy** [comment]
Hi @scottjpearson - I think it should be up to the module to determine to 'scope' of the call.  If it is a one-time call, then the module should set a property to the EM data table and ignore future calls - or am I missing something?

Depending on performance (e.g. how much server resources does it take to load and iterate through 50 ExternalModules and read their configs?) to determine the 'maxmimum frequency' for EM crons (every minute/15min/hour) - maybe we say every hour initially and then can make it faster if we find it is super efficient :-)

@taylorr4 - I like your idea for 'simplicity' in the definition, but think it might be more future-proof to include key-value pairs for options just in case someone down the road invents a need for it.  For example, in the future you might want to add an additional attribute, such as a 'max_lifetime' or 'error_handler' or something like that...

How about:

```javascript
"cron": [
  {
    "name": "My cron to check for x",
    "method": "module_cron_method"
  },
  {
    "name": "Cleanup cron to remove temp files",
    "method": "module_cron_cleanup_method"
  }
]
```

Presumable each method would do a `getSystemSetting("last_cron_run")` to determine the last time it ran and compute a delta to determine if it should do anything on this cron call.

Cron methods would be 'global' to the EM and not project-based.  Out of curiosity, is there an easy ways for a 'system-level' EM method to scan and instantiate each 'project-level' configuration of itself?  For example, if EM5 was called 'getHighTemp' and it was enabled for 15 projects - how would it go about determining which 15 projects were using it (haven't tried to do this yet)

PS - loving this collaborative discussion!

**Comment by taylorr4** [comment]
@123andy, i think reading through even 100 config files would not affect much and would likely run in less than a few seconds (even with db calls in between). Every 10-15 minutes might be okay (just a hunch) as the interval for the EM cron itself.

I like the idea of using getSystemSetting for global module cron, and we could also use getProjectSetting for project level crons in determining their last run time. I would assume that we would need some kind of "interval" attribute (in minutes) for each cron listed in the module's config though. This all seems doable and without even having to add new db tables. I guess we can check to see if the config has the "project-settings" attribute to determine if it is project-level or not, but that may or may not really dictate whether REDCap should automatically have the cron iterate through each project using the module. 

So instead, maybe each cron in the config could also have an attribute "project-level" as a boolean (or something to that effect). So perhaps in the end you have something like below. Then you could easily have project-level and system-level crons for a single module.
`"cron": [
  {
    "name": "Project-level cron to check for x",
    "method": "module_cron_method",
    "interval": 30,
    "project-level": true
  },
  {
    "name": "Global cron to remove temp files",
    "method": "module_cron_cleanup_method",
    "interval": 1440,
    "project-level": false
  }
]`

**Comment by mmcev106** [comment]
We could easily add a method to determine which projects a particular module is enabled for (based on getSettings()).  With that in mind, I'm not sure a "project-level" flag is necessary, since a system level cron job could easily call such a method to perform any project specific tasks (and even base them on module specific logic).

Specifying just an "interval" seems simple at first glance, but I think it might actually be more complicated depending on the implementation.  If possible, it would be much simpler to run tasks at specific times like a cron, instead of having to keep track of the last run time of each task.  Also, some tasks might have to run at a particular time of day.

It may be more helpful to think in terms of requirements.  I'm guessing the follow would be our most common needs:
- Every 15m, 30m, or 1h
- Daily on a certain hour
- Weekly on a certain day, and perhaps hour
- Monthly on certain day, and perhaps hour
- Yearly on a certain day, and perhaps hour

Traditional cron syntax supports these cases well.  However, we could go with more user friendly syntax that is easily translated into cron-like timing.  For example:

`"cron": [
  {
    "name": "Every 15m",
    "method": "some_method",
    "interval": "15m"
  },
  {
    "name": "Every 30m",
    "method": "some_method",
    "interval": "30m"
  },
  {
    "name": "Every hour",
    "method": "some_method",
    "interval": "hourly"
  },
  {
    "name": "Daily",
    "method": "some_method",
    "interval": "daily"
    "hour": 9
  },
  {
    "name": "Weekly",
    "method": "some_method",
    "interval": "weekly"
    "day": "Saturday"
    "hour": 23
  },
  {
    "name": "Monthly",
    "method": "some_method",
    "interval": "monthly"
    "day": 15
    "hour": 2
  },
  {
    "name": "Yearly",
    "method": "some_method",
    "interval": "yearly"
    "month": 1
    "day": 1
    "hour": 0
  }
]`

**Comment by scottjpearson** [comment]
How about MM/DD/YYYY HH:MM with a wildcard for unknown:
*/15/* *:00 for the 15th of every month at the top of every hour.

AM/PM vs. military time doesn’t matter to me.

??


Scott J. Pearson
REDCap Data Core Programmer
Vanderbilt Institute for Clinical and Translational Research (VICTR)
615-322-6039 (o)

**Comment by 123andy** [comment]
Hi guys,

**Project vs. System**
I don't think we need project-level cron - I would say that the 'system-level' cron for an EM would be in charge of handling project-level issues.  There could be project-level parameters that could be configured and the system level cron would have to respect those, but that is all up to the EM developer.

**Syntax**
Mark - I love the idea of a more 'cron-like' behavior - including specific times, but currently the 'redcap cron' is sliding and presumably the EM cron would be a child job of the REDCap cron.  So, if you schedule a cron every 24 hours but it takes 10 minutes, you will shift up 10 minutes each day - after a week it will be happening an hour later.  Option one is to have each system-level EM store the last-run-time and figure out an appropriate delta in code, on the assumption the cron method gets called every 15 minutes or so.  Option 2 is to try and pull that logic into the config and cron manager.  I like option 2 if you think it can be done.

One challenge would be to rework/add to the base REDCap Cron so you can reliably have a 'start time' regardless of execution time.

A second challenge is forking jobs across many EMs.  What if one EM has 50 projects that have a record-level check taking place (similar to the datediff+today check).  It could take 15 minutes for that cron to finish.  If all EMs with crons are in a sequential queue, this could cause issues.  Is it possible to quickly determine a list of EMs that have crons and then fork out the call to each one so they run concurrently?  Or, is this a bad idea?

(In truth, I've done all my cron'ing of plugins using the linux cron and not the REDCap due to the floating start time.  I like being able to look at my logs and know that at 12:15AM this event is supposed to happen every day.)

**Comment by 123andy** [comment]
Just had one more thought - we could also just make each EM cron a row in  redcap_crons...
```javascript
{
    //"cron_name" would be automatically set as something like 'EM-45'
    "cron_description": "Weekly check for My Fancy EM",
    "method": "some_method",
    "cron_frequency": "120" // in seconds
    "cron_max_run_time": "500",
    ..
  }
```
maybe not as powerful, but certainly easier to implement.  Maybe you would write the cron_id generated as a system variable so it could be updated if params changed.  Dunno - whatever you guys think is best.

**Comment by taylorr4** [comment]
I agree that project-level cron logic doesn't really make sense, plus it adds a lot of complexity.

As much as i originally disliked the idea of putting individual modules with a cron into the redcap_crons table, this seems much more appealing and simpler to me now (maybe after hearing all the complexity from this that might come about if we don't). So how about this?

1. If a module is enabled globally, and it has a cron listed in the config, a new row gets added to redcap_crons table and sets its frequency and max run time based on the config. I could add a new column to the table called external_module_id (as a foreign key) to more easily deal with this.
1. And if the module is later disabled, the cron in the table would get set to disabled.
1. The EM crons would get prioritized last with regard to REDCap's internal crons so that they wouldn't affect normal REDCap functionality.

How does that sound?

**Comment by 123andy** [comment]
I think that should be fine.  A new FK makes more sense, then you can have both a 'name' and 'description' in the config.  We can also then see last_run_time to look for problems...

So, going back to my disaster scenario of a really long EM job... 
Imagine the EM job takes 40' to run but is queued up every 15 minutes.  Let's assume you set the cron_instances_max to 2.

    T0 - Instance1 starts
    T15 - Instance1 still has 25' left and is running.  Start Instance2.
    T30 - Instance1 has 10' left, Instance2 has 25' left.  We have exceed our max-instances

**I think this should throw an exception for the module that results in an admin email.**
In fact, I think in general if this ever happens in REDCap, it should somehow notify the admins.  I was unaware of the datedif+today never finishing for a while...

Instance3 would not start at T30.
    T45 - Instance 1 is done, Instance2 has 10' left, we start Instance1b...

What about a job exceeding the max_run_time?  I suppose that should also throw an exception.

**Comment by mmcev106** [comment]
I think we're on the right track.  The biggest complication I am seeing is how to handle changes to cron settings when modules are updated.  If everyone always uses the "Change Version" feature to update modules, we could implement a hook to keep the redcap_crons table in sync.  However, I'm not sure that's realistic.  Our team currently just rsyncs changes for most of our updates, so other people likely will too.  I wonder if we should just store dummy values for **cron_frequency** and **cron_max_run_time**, then pull the actual values from **config.json** everytime.  Another option would be to track the mtime for **config.json** constantly, and update redcap_crons whenever we detect that it changes (not sure I like that).

Also, if we decide this use case doesn't fit redcap_crons well, we could store EM cron data in the redcap_external_module_settings (we already have a couple of "reserved" settings).  That might be more appropriate anyway, since that table is intended for module specific data.

**Comment by 123andy** [comment]
Hey Mark - how can you change a version for a module just with rsync...  Doesn't it require you to enable a module in the gui and 'change version' which updates the version entry in the module_settings table?

When that version is enabled (and permissions are verified) - couldn't the permissions page just be expanded to have a cron section where it says it will add the following cron job or it will update the existing cron job with new settings?

**Comment by taylorr4** [comment]
@123andy, i believe Mark's just talking about pulling the code down from the git repo directly to the server to update it.

**Comment by 123andy** [comment]
Well - if you change the config.json that way, it should probably be a new version, no?

**Comment by scottjpearson** [comment]
I sometimes update only the config.json (without a version change) for a small bug fix in production, or more commonly, for a change on the test server.

Scott

**Comment by 123andy** [comment]
I guess if you were really worried about it - you could build in a 'checker' in your cron method that queried the redcap_crons table and compared against the current config... seems like an edge case.

**Comment by taylorr4** [comment]
These are all good ideas and great input. I don't think putting dummy values in the crons table would be very efficient because those values are really what drive the job timing interval, so it would have to check each module's config to determine if it needs to run, which wouldn't be good to run every minute. But i have a better alternative: when a module is enabled, it will have its crons and their attributes added to the redcap_crons table. Then when an EM cron is executed, it can double-check its own config to ensure that the values are the same as in the crons table, and if not, it halts and corrects its values in the table. And to add to that, I can add an internal cron to REDCap that can check every 15 or 30 minutes or so that will sift through all EM configs to verify their cron values and auto-fix them if out of sync. That way it can always be actively auto-correcting EM crons in case people like Scott are modifying them directly on the server. :) That should deal with the synchronicity issues.

So i propose those things, and thus suggest the cron format below for the config. Am i forgetting anything? Also, a couple questions:
1. We are still going with the idea that we can have multiple crons per module, right?
1. Should we assume that the method is always in the core module class for that module?

```
"crons":[
{
    "cron_name": "cron1" // This must be a unique cron name *only within* the module
    "cron_description": "Weekly check for My Fancy EM",
    "method": "some_method",
    "cron_frequency": "120" // in seconds
    "cron_max_run_time": "500", // in seconds
 },
{
    "cron_name": "cron2" // This must be a unique cron name *only within* the module
    "cron_description": "Weekly check for My Fancy EM",
    "method": "some_other_method",
    "cron_frequency": "43200" // in seconds
    "cron_max_run_time": "1200", // in seconds
 }
]
```

**Comment by mmcev106** [comment]
We have a deploy script that uses rsync, tags the release in git, deploys to multiple REDCap nodes, and a few other fancy things.  Yes, that would arguably be a new version, and we could change our process, but I'm not sure that's enforceable at other institutions.  The main reason I brought that up is that it illustrates how storing cron settings in the database in addition to config.json adds a layer of complexity that might be more hassle than it's worth.

At the moment I'm feeling pretty strongly that the simplest solution is just to loop through all the config.json files whenever cron runs, and store any data related to cron in the redcap_external_module_settings table.

Thoughts?

**Comment by taylorr4** [comment]
See my comments above.

**Comment by mmcev106** [comment]
I have no concerns if the parameters in config.json are checked on every run.  I think it definitely makes sense to support multiple crons per module, and also to assume those methods will be on the module class.

**Comment by 123andy** [comment]
Sounds great, Rob.

**Comment by mmcev106** [comment]
Closing, since Rob has added this feature!

https://github.com/vanderbilt/redcap-external-modules/pull/31
