### ISSUE TITLE
Understanding the Framework class

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#193]
Hi @mmcev106 

Was in a call with @kcmcg and discussing how we should view the new Framework class and realized we didn't have best practices nailed down.  Wondering if you could opine on the subject a bit...

1) Seems like we need a table like:
REDCap Version #,  External Module "Version", Framework Version(s) Supported, Comments

I'm not aware if we have 'versions' of external modules, but we could at least have the commit for which versions were pulled into what versions of REDCap.  How often does Rob integrate the EM repo into REDCap?

2) As a developer, if I identify a bug or missing feature, what is the decision tree that helps me make the best pull request:

- If the issue is with the management of EMs or configuration of EMs, it is not part of the framework (e.g. config branching logic) - so pull requests are made against the existing 'testing' branch.  Backward compatibility is a challenge here..
- if the issue is with a helper method in the abstract EM class, then the new 'framework' classes may apply:
   - if it is a new method with no compatibility issues, should it be released to the core class or only to the framework class?  
   - If framework class, which version?  If only the framework class, then we are essentially saying our module will only work with a future version of REDCap yet to be released...  It seems we should be applying more pressure on REDCap sites to stay current with REDCap updates.
   - If a change fixes a problem or improves an existing method so there could be compatibility issues, I assume this means you should use the framework classes, but in this case must you make your pull request to the framework that hasn't yet been released?

**Comment by mmcev106** [comment]
1. That sounds nice.  I'm not sure the pieces would fit together quite like that at the moment, but that might just be because I'm so far underwater with just keeping the lights on that I can't see very far.
    - There is no "External Module Version".  The framework code is just considered part of the REDCap version.  I typically create PRs to Rob on a weekly basis, but that's delayed at the moment because of an edoc IDs reference issue we're working on.
    - I wonder if it would be more useful to display the latest framework version supported within REDCap (perhaps on the built-in module docs page).
    - I might need input to understand how other people would use this feature to have significant input.  Personally, I'd just always create new modules with the latest framework version in the github docs.  If I got an error saying it wasn't supported on my REDCap version, I'd just bump down the version number until it was.
2. This is a work in progress, but I believe the decision tree is simply:  **Always make PRs to the `testing` branch.  New module instance related functionality should likely be added to the latest framework version class.  To ensure backward compatibility, a new framework version should be created for any breaking changes**.  While I personally think it makes sense to always add new functionality to the latest framework version to encourage updating modules, it doesn't really matter.  You'd still have to update to the latest REDCap version to use any new changes regardless of what framework version class they're added to.

**Comment by mmcev106** [comment]
Closing since this hasn't been updated in months.  Feel free to reopen.

**Comment by mmcev106** [comment]
After thinking about framework versioning more over the past six months, I think it makes the most sense to add all new functionality to framework version 2.  Greater framework versions will only need to exist for breaking changes to existing functionality.  I just moved all methods added to v3 to v2, and plan on putting the minimum REDCap version in the docs for those methods once they make it into a release.
