### ISSUE TITLE
AbstractExternalModule::getProjectSetting  with repeatable fields returns array instead of null

### ISSUE THREAD

**Issue by biggeeves** [vanderbilt/redcap-external-modules#229]
Using the following setting in the config.json file:

```
      "key": "validation_format",
      "name": "Validation Format<br> (# = any number, $ = any letter, * = Anything)",
      "required": false,
      "type": "text",
      "repeatable": true
```

will return the following array instead of null: 

`Array ( [0] => )`

While using the config below will return null

```
      "key": "validation_format",
      "name": "Validation Format<br> (# = any number, $ = any letter, * = Anything)",
      "required": false,
      "type": "text",
      "repeatable": false
```
It is easy to reproduce.  Create a repeatable field in the config, use AbstractExternalModule::getProjectSetting  and output the result when no value is set.  Then switch to "repeatable": false. and the value returned by getProjectSetting is Null. 

The documentation states: If no value is set, null is returned.

Null should be returned for repeatable fields when no value(s) has been stored.

**Comment by grezniczek** [comment]
I guess the reason for this is that in case of repeatable elements, there is _always_ at least the first instance present (index 0). The value of it may be null (which is what you get) Imagine two instances, but the first being null. The return value would be:
`Array ( [0] => , [1] => "something" )`

While one could argue about the format values are returned in general, I think this is actually the correct and logical way to handle this. There always exists an instance with index 0, and the array will include an element for each instance. Otherwise the return format for repeatable settings would differ depending on whether there is a value for the first instance or not.

**Comment by mmcev106** [comment]
Based on the info here I think @grezniczek is on the right track.  @biggeeves, I'd be curious to hear more if you still think this needs to change.  If I haven't heard anything in a week I'll update the docs to reflect the actual behavior and close this out.  Thanks for the interest regardless!

**Comment by mmcev106** [comment]
The docs [have been updated](https://github.com/vanderbilt/redcap-external-modules/commit/d1868c411a436a41c44f2230c0b95c299c25d6ca).  Feel free to reopen this issue if anyone sees fit.
