### ISSUE TITLE
Missing module folder throws odd error

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#29]
If you have a module enabled and then remove its folder from your server, you get an error about the module MUST specify a 'namespace' in it's config.json file.  This is misleading as the real issue is that the entire config.json doesn't exist anymore and this module entry in the redcap_external_modules table should probably be removed...

**Comment by mmcev106** [comment]
I'm having trouble reproducing this on testing or master.  Are you seeing it against the latest code?  If so, what steps are required to reproduce it? 

I don't think we want to remove rows from the redcap_external_modules table, since that would orphan the settings.  I think we want to keep the settings indefinitely, since it may not be possible to tell accidental and intentional removals apart.  There may also be cases where people want to re-install an intentionally deleted module and retain their previous settings.

Thanks very much for the bug reports!

**Comment by 123andy** [comment]
I just updated to the most recent 'testing' branch.    I thought I had done that prior to this error - but I am unable to replicate.  So, consider it a goose chase...
