### ISSUE TITLE
External Modules defining PAGE constant

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#30]
https://github.com/vanderbilt/redcap-external-modules/blob/2ab21809cb50a134681ddbc122c8b07bd50c3690/classes/ExternalModules.php#L937

After enabling External Modules on our server, I noticed that many of my plugins had a different value for the page column in the redcap_log_event table.

I believe that the order of including ExternalModules is causing the PAGE variable to be assigned in cases where it wasn't previously.  The logging class used to address this with:
`$page 	 	= (defined("PAGE") ? PAGE : (defined("PLUGIN") ? "PLUGIN" : ""));`

but now it is already defined so it gets the new value.  This caused a number of my scripts to have issues (since autonotify used the log and filtered by 'PLUGIN' as an index to speed queries.  I'm not all against it - I fixed it here, but am worried about other people that might be using my plugins having all hell break loose as soon as they enable this.

https://www.dropbox.com/s/3wv4ch2xn8octtw/2017-09-19_0946.png?dl=0

**Comment by mmcev106** [comment]
@taylorr4 and @mcguffk, the line to set the PAGE to the request URI if it is not defined has been in place since November (early prototyping).  I'm not sure if the more recent change of including external modules directly in REDCap's code (instead of in the hooks file) would have changed this behavior.  Regardless, I'm thinking we should remove this and leave setting the PAGE up to REDCap.  Before I do that, I might want to look through all our modules to make sure they aren't expecting PAGE to be set.  Do either of you have any thoughts/concerns before I remove those lines?

**Comment by taylorr4** [comment]
@mmcev106, that seems fine to me.

**Comment by mcguffk** [comment]
I can't think of anywhere that I would have used PAGE on an external module. I think a quick grep should be good to be certain.

I agree that we should leave it to REDCap and should update any modules if they are relying on External Modules setting it a certain way.

**Comment by scottjpearson** [comment]
I kinda want to say that I have.

Scott J. Pearson
REDCap Data Core Programmer
Vanderbilt Institute for Clinical and Translational Research (VICTR)
615-322-6039 (o)

**Comment by mmcev106** [comment]
Yes, we are currently depending on specific pages being set in a few places in external modules.

Although it does break Andy's code, I do think the current behavior makes the log table much more useful (since it actually logs what page you're on).  @taylorr4, would it be worth considering leaving this behavior as is?  If so, should we move this code from external modules to core REDCap?

**Comment by taylorr4** [comment]
I think we can modify that line in REDCap from
`$page 	 	= (defined("PAGE") ? PAGE : (defined("PLUGIN") ? "PLUGIN" : ""));`
to
`$page 	 	= (defined("PAGE") ? PAGE : "");`
Honestly, it appears that it's not even useful for plugins anyway because PAGE is already defined in a plugin when you get to that line of code, at least in the latest version. I'm wondering if this has changed in recent years. This is not something we've ever used really, so i don't mind modifying it to the line above. Unless anyone has objections, i'll put this change into REDCap 7.6.8, which will be the next release. That seems like that would resolve this issue, right?

**Comment by 123andy** [comment]
I fixed my code – so no problem leaving it.  Just wanted to make you all aware…

**Comment by taylorr4** [comment]
Okay, @123andy, sounds good. I realized that my code suggestion above didn't even make much sense (was thinking of something else). But @mmcev106 dropped by and we chatted about the usage of PAGE, and he and @mcguffk will chat about it and get back to me regarding whether or not we want to change its usage/definition in EMs.

**Comment by mmcev106** [comment]
We are indeed using this functionality in a few modules.....and I must say it's darn useful.  At the moment I don't see us ever having any pressure (or funding) from clients to change this, so I'm leaning towards just leaving it as is.  Does anyone think that's a bad idea?

**Comment by 123andy** [comment]
I actually think having the page represent the 'real page' makes a lot of sense...  the Plugin line in the log is kind of silly.  Actually, what the log needs is another enumerated field that indicates whether an action was performed by a user / survey participant / plugin method / api method...

**Comment by taylorr4** [comment]
@123andy, too bad the logging tables are too big at this point to add new columns. So what would you propose in place of the line: `$page = (defined("PAGE") ? PAGE : (defined("PLUGIN") ? "PLUGIN" : ""));`?

**Comment by 123andy** [comment]
My reading of this thread makes me think we are leaving it as it was when I opened it, right?  This means that basically the PAGE is going to be set via the initialization of the External Modules if it wasn't already set prior by the main redcap code.

If true, then all plugins will basically already have PAGE set to something like "/plugins/foo/bar.php" after including redcap_connect.  I actually this this makes sense, since it is the page and that is the column title.

Sorry if I'm missing something...    I do think that logging API vs. non-API actions in the user's logging view is a real issue that could warrant an alter to the redcap_log_events table, but I hear you that this could be a long one!

**Comment by mmcev106** [comment]
I believe MySQL has made some progress on what ALTER TABLE operations it can do "in-place" in recent years.  Adding a column is one of those in the table on this page:

https://dev.mysql.com/doc/refman/5.7/en/innodb-create-index-overview.html

We're still on 5.1, and I'm not sure when that feature was added.  I mainly just wanted to throw that out there for future consideration.

**Comment by taylorr4** [comment]
Yeah, I’m not concerned for us but for the other 2500 places where something could go awry when modifying a huge table during an otherwise routine REDCap upgrade, especially since people can be on any number of MySQL versions and flavors that may or may not perform such in a quick or efficient way. I remember when we added the instance column to redcap_data a couple years back, Andy Arenson said it took 20 hours for that one query to run, and his installation is 10x smaller than ours.

**Comment by mmcev106** [comment]
It sounds like we might as well close this issue for now.  Feel free to re-open it if you'd like to continue the discussion at this time.
