### ISSUE TITLE
Incorrectly assuming that IP address = localhost

### ISSUE THREAD

**Issue by taylorr4** [vanderbilt/redcap-external-modules#33]
I worry that this may display PHP error information to end-users on some REDCap installations using external modules. There are a decent amount of valid REDCap production installations that use an IP address for their REDCap web address (rather than a domain name). Perhaps there is another way to detect a dev environment, such as looking only for internal IPs, such as 10.X.X.X or 192.168.X.X. Thoughts?

https://github.com/vanderbilt/redcap-external-modules/blob/ae148bba624efd8f986d3a216ed0e4b7a6822b14/classes/ExternalModules.php#L108-L116

**Comment by 123andy** [comment]
Why not put a flag in redcap_config that allows you to declare an 'instance' of redcap to be in development mode?

Related - one other 'flag' I wanted to request would be to 'force localhost over http' - this has come up in the myCap app, but could also come up with EM's if people use API methods to try and do actions on the server.  For us, since https is stripped off at the load balancer, if our server tries to do https://localhost we have issues so we have to switch to http.  This, by the way, also breaks the API playground for us...

**Comment by taylorr4** [comment]
@123andy, regarding 'force localhost over http', i've not heard of that being an issue myself, but if you want to put in a pull request in REDCap for it, be my guest. 

@mmcev106, right now in REDCap all i have is isDev(), which checks if the server is either  localhost or *my* specific desktop's IP address. It, like isLocalhost() in ExtMods, merely turns on error reporting.

So regarding a "dev" flag to denote development mode of a REDCap instance, i think that is reasonable. We'll look into adding that soon, and then perhaps that flag can be utilized here in isLocalhost(), if that sounds good. Thanks!

**Comment by mmcev106** [comment]
Sounds good to me!  Since you're added the flag, I can make the EM change.

**Comment by taylorr4** [comment]
Okay, i went ahead and just put in a pull request (https://github.com/vanderbilt/redcap-external-modules/pull/34) for this since i was implementing it on the REDCap side.

**Comment by mmcev106** [comment]
Thanks!
