### ISSUE TITLE
Questions around getUrl file whitelisting

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#333]
So, we have this really talented penetration company that is beating on our server...  They really don't like any sort of file-via-parameter things, such as:  `&page=pages/foo.php`.   I'm beginning to be sold on the idea that we should be much more specific about how we allow the EM framework to include or exclude files.

A few ideas:
- explicitly whitelist suffixes for getUrl includes?
- explicitly whitelist directories in the module

Thoughts?

**Comment by mmcev106** [comment]
I could see whitelisting working.  With that said, I'm a little confused since the page parameter is only able to access files inside the module directory (where they can also be accessed directly).  Is there an actual issue, or is the pentest company fixating on a non-issue?

**Comment by 123andy** [comment]
We use gitsubrepo to clone our EMs into our releases.  This leaves a .gitsubrepo file in each EM directory which can be read with this method.  While it isn't directly a security risk, it is an example of how one could fish for files.

I also saw that the rather popular Admin Dashboard EM uses smarty and it is actually writing php files into the external module directory where it exists and then those are being parsed...

I like the idea of being able to say something like:
```json
{
  "get-url-page-whitelist": [
    "*.css",
    "*.js"
  ]
}
```
If present in the json, it would force those checks...
Maybe something using [fnmatch](https://www.php.net/manual/en/function.fnmatch.php) syntax?

**Comment by 123andy** [comment]
For a potential vulnerability - I've seen cases in plugins where people have variables in a .ini file or in a .config file, for example, that might contain api tokens, etc..  I can't think of a reason someone would put this into an EM folder but I'm guessing some developers have.
Being able to view the contents of all files in the EM folder that aren't php is probably not advisable...

**Comment by mmcev106** [comment]
Can't any file in a web accessible directly be accessed directly by the browser anyway?  It seems like the root cause of these risks might not be module or REDCap related, and would apply to legacy plugins & hooks and other projects/sites/servers as well.  On our servers we...
- Store credentials in files outside the web root or in the database.
- Only give the apache user read access to web directories.  Write access is limited to temp directories & edocs.
- Exclude git related files and other sensitive files in our deploy scripts

**Comment by 123andy** [comment]
I think that is all good practice.  For us Apache prevents file access unless authenticated, so this provides a non-authenticated path to files which are, in many places, already public...  But this is in part our own problem...

**Comment by 123andy** [comment]
Out of curiosity, how do you do your build and deploy process?  Would you be willing to present on that?

**Comment by mmcev106** [comment]
Our different teams have different solutions.  The best are likely the ones that use docker.  My team uses a deploy.json file in each project directory which contains configuration parameters that pass to rsync via a thin PHP script wrapper.  The only build process is whatever commands are configured to run first in deploy.json (often just `composer install`).  It's far from ideal, but it works OK.  I guess I wouldn't be opposed to presenting on it, although I'd be adding qualifiers all over the place on what I think we should be doing instead, heh...

**Comment by mmcev106** [comment]
My team only deploys our own code (modules, plugins, etc.) at any time of our choosing.  Rob deploys REDCap itself, and I believe that process is quite manual still.  We have a hard time getting time approved for things that don't directly translate into value for users...

**Comment by grezniczek** [comment]
You could argue that a streamlined, efficient (a.k.a automated) deploy pipeline saves a lot of time in the long run (and will improve quality/avoid mistakes). This results in more time overall that can be converted into customer value. Same with infrastructure upgrades in general. They usually pay off and result in the capability to produce more value, faster, down the road (because some groundwork has been done). Of course, it's often not easy to judge how much is justified, how much of it will actually be reusable.
But I guess I am preaching to the choir here.

In any case, it'll be a hard sell. You could always make it a hobby, though ;)

**Comment by mmcev106** [comment]
Yeah...  We also have to pick our battles, and I'm afraid our deploy process is not at the top of anyone's priority list currently.  @grezniczek, I am amazed by your stamina.  I'm pretty burnt out when I get past 40 hours of intense work each week (especially while staring at a screen).

**Comment by grezniczek** [comment]
Luckily, my workload is quite diverse. This helps. Also, I function in phases. Some more intense, others less so. I guess I am currently in a more intense one.

**Comment by mmcev106** [comment]
@123andy, I guess I'll close this for now since it doesn't quite relate to the standard web server setup.  I'm happy to review/merge a PR for this even if it's specific to your authentication setup.

**Comment by 123andy** [comment]
I'm fine with closing it, but I do think the point is still valid.  If we do a redesign of the EM framework and ESPECIALLY if REDCap finally abandons the redcap_vx.y.z upgrade urls, then we should move external modules to a path outside of the www root.
