### ISSUE TITLE
Error enabling module with default system checkbox value of checked

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#52]
I seem to be getting errors enabling an ext-mod that has a system checkbox that defaults to 'true'.  

```$moduleInstance->setSystemSetting($key, $default);``` throws an error because the parent external module hasn't been initialized so the default cannot be set to the database in the abstractExternalModule class...

```[message:protected] => Cannot create module instance, since the module with the following prefix is not enabled: module_name```

**Comment by taylorr4** [comment]
@123andy, are you sure you setting the checkbox's default value as *true* and not "true" (wrapped in quotes) in the config.json? I tested enabling a module with the config below on the current "testing" branch, and it didn't have any problems.

``` json
"system-settings": [
      {
         "key": "test1",
         "name": "Checkbox default test",
         "type": "checkbox",
         "default": true
      }
 ],
```

**Comment by 123andy** [comment]
I had true without quotes - in the ajax it was sending a '1'.  Not sure…  I'll see if I can pull latest version and try again…

-A



Andrew Martin, PhD
Stanford University School of Medicine

**Comment by mmcev106** [comment]
Closing since this hasn't changed in about a year.  Feel free to re-open.

**Comment by dconlan** [comment]
I am seeing this error, for a system field with a default value.

I did not see the problem with redcap 8.8.1, but both 8.10.4 and 8.11.2 are giving me the error.

The module I am trying to enable is fhir-ontology-provider.

I have a solution, though I don't know if it has other consequences.

In the enableForProject function in ExternalModule.php there is code

```
     self::initializeSettingDefaults($instance);
     self::setSystemSetting($moduleDirectoryPrefix, self::KEY_VERSION, $version);

     self::cacheAllEnableData();
```

The cacheAllEnableData creates an array of enabled versions and this is what is checked by the getEnabledVersion when the code attempts to create an instance with no version.

My thinking is to rearrange these three lines, so that the version is set before the defaults.
The code would become
```
     self::setSystemSetting($moduleDirectoryPrefix, self::KEY_VERSION, $version);
     self::cacheAllEnableData();
     self::initializeSettingDefaults($instance)
```
