### ISSUE TITLE
Semantic Versioning no longer supported

### ISSUE THREAD

**Issue by tbembersimeao** [vanderbilt/redcap-external-modules#57]
[Semantic versioning](http://semver.org/) on modules (e.g. `v1.0.0`) is no longer supported. I think it should be allowed since that's the pattern used by REDCap core.

**Comment by mmcev106** [comment]
To my knowledge, the semantic versioning restriction is only on the module submission form.  @taylorr4, what are your thoughts on expanding that restriction?

**Comment by taylorr4** [comment]
@mmcev106, i think the restriction is in the EM code too. I just copied my votecap_v1.2 directory and named the copy votecap_v1.3.0, and it comes up as a blank value in the version drop-down (it's empty) in the module manager popup. So that new version is not able to be enabled. 

So it appears that EM cannot handle those yet. Please let me know if i'm missing something here. If support for this gets added into EM itself, then i'm sure we could add it into the documentation and REDCap Repo submission survey as well.

**Comment by mmcev106** [comment]
I just [added support for semantic versioning in the code](https://github.com/vanderbilt/redcap-external-modules/commit/04bdd71935f2c68bd6e289dc96a90555a28dbe99) on the testing branch.  I did NOT update the documentation, since I wasn't sure if we wanted to continue encouraging the simpler v#.# versioning.  @taylorr4, I might defer to you on that since it probably affects you the most.  Let me know if there's anything else I can do to help here.

**Comment by taylorr4** [comment]
Awesome, thanks, @mmcev106! I've now added this into the ExtMods version embedded inside REDCap, so semantic versioning will now be officially supported in REDCap 8.0.3+.

**Comment by tbembersimeao** [comment]
Thank you guys!
