### ISSUE TITLE
function redcap_every_page_top NOT firing on every page

### ISSUE THREAD

**Issue by biggeeves** [vanderbilt/redcap-external-modules#66]
Every Page Top is supposed to fire at the top of every page.  However it is not in the testing branch nor the master branch. 

To confirm the issue I wrote a small plugin that fires on every page top:

The plugin only contains this:

```
function redcap_every_page_top($project_id)
{
   echo '<div style="width:100px;height:200px;background-color:yellow;">hi</div>';
}
```

The External Module "Instance Marker" is trying to add a marker to every page.  However pages like this one, http://localhost/redcap8.0.2/redcap_v8.0.2/index.php?pid=1 do NOT fire the function redcap_every_page_top.  It does fire correctly here: http://localhost/redcap8.0.2/index.php

**Comment by taylorr4** [comment]
@biggeeves, i assume you mean "module" not "plugin", right? If you want that hook for that module to be called in a project, then the module must be enabled for that project OR it must be enabled for ALL projects. Otherwise it will not fire, which is what you're seeing. You might want to mention in your module's instructions that the module must additionally be enabled on all projects by default in order for the instance label to appear inside projects too.

**Comment by biggeeves** [comment]
@taylorr4.  I did a fresh install of another version of REDCap, moved the external modules folder over and forgot to set the "enable for all modules".  I'll close delete this issue.
