### ISSUE TITLE
short tags...

### ISSUE THREAD

**Issue by 123andy** [vanderbilt/redcap-external-modules#8]
I see that the modules code uses the <?= short tag in lieu of the <?php echo...  I'm not necessarily opposed, but this may cause some issues.  Might be good to put a config-check in to verify that short_open_tag is on - otherwise some installations are bound to have issues...

**Comment by taylorr4** [comment]
Yeah, I already added a check to ensure that you have php 5.4. Not merged yet though.

Rob Taylor

(Sent from my phone. Sorry for brevity / poor spelling.)

On Aug 6, 2017, at 4:13 PM, Andy Martin <notifications@github.com<mailto:notifications@github.com>> wrote:


I see that the modules code uses the <?= short tag in lieu of the <?php echo... I'm not necessarily opposed, but this may cause some issues. Might be good to put a config-check in to verify that short_open_tag is on - otherwise some installations are bound to have issues...

**Comment by taylorr4** [comment]
That's true, @123andy, you can just short_open_tag=On in PHP.INI. However, i believe that @mmcev106 mentioned to me before that several things are done in Ext Mods that require PHP 5.4, so it's not just an open tags issue. So given that, i assumed we would just require PHP 5.4 anyway, especially since i'm thinking of requiring it in REDCap itself sometime next year (the current requirement is 5.3 in REDCap). I don't think it's unreasonable to require PHP 5.4 for Ext Mods to work.

**Comment by mmcev106** [comment]
I should also mention that in PHP 5.4+ the "<?=" syntax works all the time (even when the **short_open_tag** config option is off).
